apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
