name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js for Backend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: npm install

    - name: Test Backend
      working-directory: ./backend
      run: npm test

    - name: Setup Node.js for Frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Frontend Dependencies
      working-directory: ./client
      run: npm install

    - name: Build Frontend
      working-directory: ./client
      run: npm run build

    - name: Build Backend Docker Image
      run: |
        docker build -t buraksefil17/project2-restaurant-backend:latest ./backend
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker push buraksefil17/project2-restaurant-backend:latest

    - name: Build Frontend Docker Image
      run: |
        docker build -t buraksefil17/restaurant-client:latest ./client
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
        docker push buraksefil17/restaurant-client:latest